import { ThemeProvider } from "@/components/theme/theme-provider"
import ClientOnlyLayout from "@/components/global/client-only-layout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/dashboard/sidebar";
import { Navbar } from "@/components/dashboard/navbar";
import { SidebarProvider } from "@/contexts/sidebar-contexts";
import { Footer } from "@/components/dashboard/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ClientOnlyLayout>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              >
              <div className="flex min-h-screen bg-muted/30">
                <SidebarProvider>
                  <Sidebar />
                  
                  <div className="flex flex-1 flex-col">
                    <Navbar />
                    <main className="flex-1 p-6">
                      {children}
                    </main>
                     <Footer />
                  </div>
                </SidebarProvider>
              </div>
            </ThemeProvider>
          </ClientOnlyLayout>
      </body>
    </html>
  );
}
